config/routes.rb
LunchPanoply::Application.routes.draw do
  root to: 'static_pages#index'

  devise_for :admins

  devise_for :employees, 
             :controllers => { 
                               # :registration => "registration",
                               :omniauth_callbacks => "employees/omniauth_callbacks" 
                              }

  namespace :api_clients do
    resources :menu_items, defaults: { format: 'json' }
  end                           

  resources :companies

  resources :employees do
    resources :sessions
    resources :comments
    resources :favorites
    # resources :companies
  end

  # resources :companies do
  #   resources :employees
  # end

  resources :venues do
    resources :menu_items
  end

  resources :menu_items

  # resources :menus do
  #   resources :menu_items
  # end

  # resources :sessions, only: [:new, :create, :destroy, :failure]
  # resources :identities
  # match '/auth/:provider/callback', to: 'sessions#create'

  # match '/signup',  to: 'employees#new', as: :sign_up
  # match '/signout', to: 'sessions#destroy', as: :signout
  # match '/signin',  to: 'sessions#new', as: :signin

  # match '/auth/failure', to: 'sessions#failure'

  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_filter :get_venue
  before_filter :get_menu, except: [:index, :new, :create]

  def index
    @menus = @venue.menus
  end

  def new
    @menu = @venue.menus.build
  end

  def create
    @menu = @venue.menus.build(params[:menu])
    if @menu.save
      redirect_to([@venue, @menu], success: 'Menu created!')
    else
      render(:new, error: 'There was an error processing your menu')
    end
  end

  def show
  end

  def edit
  end

  def update
    if @menu.update_attributes(params[:menu])
      redirect_to([@venue, @menu], success: 'Menu updated!')
    else
      render(:edit, notice: 'There was an error updating this form')
    end
  end

  def destroy
    @menu.delete
    flash.now[:notice] = 'You sure?'
    redirect_to(venue_menus_path(@venue))
  end

  private
  def get_venue
    @venue = Venue.find(params[:venue_id])
  end

  def get_menu
    get_venue
    @menu = @venue.menus.find(params[:id])
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/edit.html.erb
<h1>Menus#edit</h1>
<p>Find me in app/views/menus/edit.html.erb</p>

app/views/menus/index.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1>Menus</h1>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    <div>
      <%#= button_to 'Add a menue', class: 'btn btn-large btn-primary' %>
      <%#= link_to 'Add a Menu' do %>
        <!-- <button class="btn btn-primary" style="width: auto%;">Add a menue</button> -->
      <%# end %>
    </div>
    <div class="content" style="margin-top: 10%; height: 600px;">
     <div class="table-responsive">
     <table class="table table-bordered table-striped">
      <tr>
        <th>Entrees</th>
        <th>Images</th>
        <th>Prices</th>
        <th>View</th>
        <% if current_employee.try(:admin?) %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
      <% unless @menus.blank? %>
        <% @menus.each do |menu| %>
        <tr>
          <td><%#= @menu.menu_item.name %></td>
          <td><%#= @menu.menu_item.img %></td>
          <td><%#= @menu.menu_item.price %></td>
          <td>
            <%= button_to :view, menu_path(menu), 
                          options = { 
                                      method: :get, 
                                      class: 'btn btn-xs btn-info',
                                      style: 'height: 35px; width: auto;',
                                      type: 'button'
                                     } %>
          </td>
          <% if current_employee.try(:admin?) %>
            <td>
              <%= button_to :edit, edit_menue_path(menue), 
                            options = { 
                                        method: :get,
                                        clasS: 'btn btn-xs btn-default',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
            <td>
              <%= button_to :delete, menue_path(menue), 
                            options = {
                                        method: :delete,
                                        confirm: 'You sure?',
                                        class: 'btn btn-xs btn-danger',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </table>
      </div>          
    </div>
    <br />
  </div>
</div><!-- /.container -->    

app/views/menus/new.html.erb
<h1>Menus#new</h1>
<p>Find me in app/views/menus/new.html.erb</p>

app/views/menus/show.html.erb
<h1>Menus#show</h1>
<p>Find me in app/views/menus/show.html.erb</p>