config/routes.rb
LunchPanoply::Application.routes.draw do
  root to: 'static_pages#index'

  devise_for :admins

  devise_for :employees, 
             :controllers => { 
                               # :registration => "registration",
                               :omniauth_callbacks => "employees/omniauth_callbacks" 
                              }

  namespace :api_clients do
    resources :menu_items, defaults: { format: 'json' }
  end                           

  resources :companies

  resources :employees do
    resources :sessions
    resources :comments
    resources :favorites
    # resources :companies
  end

  # resources :companies do
  #   resources :employees
  # end

  resources :venues do
    resources :menu_items
  end

  resources :menu_items

  # resources :menus do
  #   resources :menu_items
  # end

  # resources :sessions, only: [:new, :create, :destroy, :failure]
  # resources :identities
  # match '/auth/:provider/callback', to: 'sessions#create'

  # match '/signup',  to: 'employees#new', as: :sign_up
  # match '/signout', to: 'sessions#destroy', as: :signout
  # match '/signin',  to: 'sessions#new', as: :signin

  # match '/auth/failure', to: 'sessions#failure'

  # match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
 class Comment < ActiveRecord::Base
  attr_accessible :content, :title, :employee_id, :menu_item_id 

  validates_presence_of :content, :title

  belongs_to :employee
  belongs_to :menu_item
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_employee

  def index
    @comments = @employee.comments
  end

  def new
    @comment = @employee.comments.build
  end

  def create
    @comment = @employee.comments.build(params[:comment])
    if @comment.save
      redirect_to(employee_comment_path(@employee, @comment), success: 'Comment created!')
    else
      render(:new, error: 'There was an error proccessing your comment')
    end
  end

  def show
    @comment = @employee.comments.find(params[:id])
  end

  def edit
    @comment = @employee.comments.find(params[:id])
  end

  def update
    @comment = @employee.comments.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to([@employee, @comment], success: 'Comment updated!')
    else
      render(:edit, notice: 'There was an error updating this form')
    end
  end

  def destroy
    @company = @employee.comments.find(params[:id])
    @company.delete
    flash.now[:notice] = 'Your sure?'
    redirect_to(employee_comments_path(@employee))
  end

  private
  def get_employee
    @employee = Employee.find(params[:employee_id])
  end

  # def get_company
  #   @company = @employee.comments.find(params[:id])
  # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div id="contact" class="section" style="overflow: hidden;">
  <div class="fixed-wrapper">
    <h1>Comments</h1>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    
    <div class="content" style="margin-top: 10%; height: 600px;">
     
      <%= form_for @comment do |f| %>
        <div class="form-group">
          <%= f.text_field :title, placeholder: 'Enter Title', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.text_area :content, placeholder: 'Enter Comment', class: 'form-control',
                          size: '5x5' %>
          <div class="clearfix"></div>
        
        <br />
        <div class="span6" style=" width: 80%; margin-left: 15%;">
          <%= f.submit 'Create Comment!', class: 'btn btn-block btn-primary' %>
        </div>
        </div>
      <% end %>          
    </div>
    <br />
  </div>
</div><!-- /.container -->    

app/views/comments/edit.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1><em style="color: #992828; opacity: .65;">Edit</em> Comment</h1>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    
    <div class="content" style="margin-top: 10%; height: 600px;">
     
      <%= form_for @comment do |f| %>
        <div class="form-group">
          <%= f.text_field :title, placeholder: 'Enter Title', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.text_area :content, placeholder: 'Enter Comment', class: 'form-control',
                          size: '5x5' %>
          <div class="clearfix"></div>
        
        <br />
        <div class="span6" style=" width: 80%; margin-left: 15%;">
          <%= f.submit 'Update Comment!', class: 'btn btn-block btn-success' %>
        </div>
        </div>
      <% end %>          
    </div>
    <br />
  </div>
</div><!-- /.container -->    

app/views/comments/index.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1>Comments</h1>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    <div>
      <%#= button_to 'Add a comment', class: 'btn btn-large btn-primary' %>
      <%= link_to 'Add a Comment' do %>
        <button class="btn btn-primary" style="width: auto%;">Add a Comment</button>
      <% end %>
    </div>
    <div class="content" style="margin-top: 10%; height: 600px;">
     <div class="table-responsive">
     <table class="table table-bordered table-striped">
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Comment</th>
        <th>View</th>
        <% if current_employee.try(:admin?) %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
      <% unless @comments.blank? %>
        <% @comments.each do |comment| %>
        <tr>
          <td><%#= @comment.title %></td>
          <td><%#= @comment.created_at.strftime('%a %B %d, %Y') %></td>
          <td><%#= @comment.content %></td>
          <td>
            <%= button_to :view, comment_path(comment), 
                          options = { 
                                      method: :get, 
                                      class: 'btn btn-xs btn-info',
                                      style: 'height: 35px; width: auto;',
                                      type: 'button'
                                     } %>
          </td>
          <% if current_employee.try(:admin?) %>
            <td>
              <%= button_to :edit, edit_comment_path(comment), 
                            options = { 
                                        method: :get,
                                        clasS: 'btn btn-xs btn-default',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
            <td>
              <%= button_to :delete, comment_path(comment), 
                            options = {
                                        method: :delete,
                                        confirm: 'You sure?',
                                        class: 'btn btn-xs btn-danger',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </table>
      </div>          
    </div>
    <br />
  </div>
</div><!-- /.container -->    

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1>Comment from: <small><em><%= @comment.created_at.strftime('%a %B %d, %Y at: %I:%M %p') %></em></small></h1>
  </div>
</div>
<div class="container" style="border-style: solid; border-color: red; border-size: 1px; overflow: hidden; margin-top: -.2%; width: auto;">
  <div class="content" style="margin-top: 10%; height: 600px;">
    <ul class="list-group">
      <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">comment title</h4>
        <p class="list-group-item-text">comment date</p>
      </a>
      <li class="list-group-item">comment title</li>
      <li class="list-group-item">comment content</li>
      <li class="list-group-item">comment date</li>
      <li class="list-group-item">view</li>
      <li class="list-group-item">edit</li>
      <li class="list-grou-item">delete</li>
    </ul>
  </div><!--/.content-->
</div><!--/.container-->