config/routes.rb
LunchPanoply::Application.routes.draw do
  root to: 'static_pages#index'

  devise_for :admins

  devise_for :employees, 
             :controllers => { 
                               # :registration => "registration",
                               :omniauth_callbacks => "employees/omniauth_callbacks" 
                              }

  namespace :api_clients do
    resources :menu_items, defaults: { format: 'json' }
  end                           

  resources :companies

  resources :employees do
    resources :sessions
    resources :comments
    resources :favorites
    # resources :companies
  end

  # resources :companies do
  #   resources :employees
  # end

  resources :venues do
    resources :menu_items
  end

  resources :menu_items

  # resources :menus do
  #   resources :menu_items
  # end

  # resources :sessions, only: [:new, :create, :destroy, :failure]
  # resources :identities
  # match '/auth/:provider/callback', to: 'sessions#create'

  # match '/signup',  to: 'employees#new', as: :sign_up
  # match '/signout', to: 'sessions#destroy', as: :signout
  # match '/signin',  to: 'sessions#new', as: :signin

  # match '/auth/failure', to: 'sessions#failure'

  # match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :city, :name, :phone, :state, :zip, :employee_id

  validates_presence_of :name, :address, :city, :state, :zip, :phone 

  validates_length_of :state, is: 2, too_long: 'please enter a two character state abbreviation',
  										too_short: 'please enter a two character state abreviation'

  validates_length_of :zip, within: 5..9, too_long: 'please enter no more than 9 characters',
                      too_short: 'please enter at least 5 characters'

  validates_length_of :phone, is: 10, too_long: 'please enter no more than 10 digits', 
  										too_short: 'please enter a 10 digit number'

  belongs_to :employee


  # def Company.total
  # end

  # def Company.by_name
  #   Company.all.order(name: :asc)
  # end

  def Company.by_newest_first
   Company.all.order(created_at: :desc)
  end

  def Company.by_oldest_first
    Company.all.order(created_at: :asc)
  end

  def Company.by_city
    Company.all.order(city: :asc)
  end

  def Company.by_state
    Company.all.order(state: :asc)
  end

  def Company.first_favorite_venue
  end

  def Company.second_favorite_venue
  end

  def Company.third_favorite_venue
  end

  def Company.first_favorite_menu_item
  end

  def Company.second_favorite_menu_item
  end

  def Company.third_favorite_menu_item
  end
end

class InvalidCompany < Company
  attr_accessible :name, :address, :city, :state, :zip, :phone

  has_many :employees
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :get_company, except: [:index, :new, :create]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to(company_path(@company), success: 'Company created!')
    else
      render(:new, error: 'There was an error proccessing your form')
    end
  end

  def show
  end

  def edit
  end

  def update
    if @company.update_attributes(params[:company])
      redirect_to(@company, success: 'Company updated!')
    else
      render(:edit, error: 'There was an error updating this form')
    end
  end

  def destroy
    @company.delete
    flash.now[:notice] = 'You sure?'
    redirect_to(companies_path)
  end

  private
  def get_company
    @company = Company.find(params[:id])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div id="contact" class="section" style="overflow: hidden;">
  <div class="fixed-wrapper">
    <h2>New Company</h2>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    
    <div class="content" style="margin-top: 10%; height: 600px;">      
      <%= form_for @company do |f| %>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Your company's name", autofocus: true, class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.text_area :address, placeholder: 'Company address', class: 'form-control', size: '5x5' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.text_field :city, placeholder: 'Company city', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.text_field :state, placeholder: 'Company state', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group field_with_errors">
          <%= f.text_field :zip, placeholder: 'Company zip code', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <%= f.telephone_field :phone, placeholder: 'Company phone', class: 'form-control' %>
          <div class="clearfix"></div>
        </div>        
        <div class="form-group" style="width: 80%; margin-left: 15%;"> 
          <%= f.submit 'Add Company!', class: 'btn btn-block btn-primary', method: :post %> 
        </div>
        <%#= render "Employee/shared/links" %>     
      <% end %>
    </div>
    <br />
    
  </div>
</div><!-- /.container -->  

app/views/companies/edit.html.erb
<div id="contact" class="section" style="overflow: hidden;">
  <div class="fixed-wrapper">
    <h1><em style="color: red; opacity: .65;">Edit</em> Company</h1>
  </div>
</div>
<div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
  <div class="content" style="height: 600px;">      
    <%= form_for @company do |f| %>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Your company's name", autofocus: true, class: 'form-control' %>
        <div class="clearfix"></div>
      </div>
      <div class="form-group">
        <%= f.text_area :address, placeholder: 'Company address', class: 'form-control', size: '5x5' %>
        <div class="clearfix"></div>
      </div>
      <div class="form-group">
        <%= f.text_field :city, placeholder: 'Company city', class: 'form-control' %>
        <div class="clearfix"></div>
      </div>
      <div class="form-group">
        <%= f.text_field :state, placeholder: 'Company state', class: 'form-control' %>
        <div class="clearfix"></div>
      </div>
      <div class="form-group field_with_errors">
        <%= f.text_field :zip, placeholder: 'Company zip code', class: 'form-control' %>
        <div class="clearfix"></div>
      </div>
      <div class="form-group">
        <%= f.telephone_field :phone, placeholder: 'Company phone', class: 'form-control' %>
        <div class="clearfix"></div>
      </div>        
      <div class="form-group" style="width: 80%; margin-left: 15%;"> 
        <%= f.submit 'Update Company!', class: 'btn btn-block btn-sucecess', method: :post %> 
      </div>
      <%#= render "Employee/shared/links" %>     
    <% end %>
  </div><!--/.content-->
</div><!--/.container-->  

app/views/companies/index.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1>Companies</h1>
  </div>
</div>
  <div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
    <div>
      <%= link_to 'Add a Company' do %>
        <button class="btn btn-primary" style="width: auto%;">Add a Company</button>
      <% end %>
    </div>
    <div class="content" style="margin-top: 10%; height: 600px;">
     <div class="table-responsive">
     <table class="table table-bordered table-striped">
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Comment</th>
        <th>View</th>
        <% if current_employee.try(:admin?) %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
      <% unless @companies.blank? %>
        <% @companies.each do |company| %>
        <tr>
          <td><%#= @company.title %></td>
          <td><%#= @company.created_at.strftime('%a %B %d, %Y') %></td>
          <td><%#= @company.content %></td>
          <td>
            <%= button_to :view, company_path(company), 
                          options = { 
                                      method: :get, 
                                      class: 'btn btn-xs btn-info',
                                      style: 'height: 35px; width: auto;',
                                      type: 'button'
                                     } %>
          </td>
          <% if current_employee.try(:admin?) %>
            <td>
              <%= button_to :edit, edit_company_path(company), 
                            options = { 
                                        method: :get,
                                        clasS: 'btn btn-xs btn-default',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
            <td>
              <%= button_to :delete, company_path(company), 
                            options = {
                                        method: :delete,
                                        confirm: 'You sure?',
                                        class: 'btn btn-xs btn-danger',
                                        style: 'display: inline;',
                                        type: 'button'
                                       } %>
            </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </table>
      </div>          
    </div>
    <br />
  </div>
</div><!-- /.container -->    

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<div id="contact" class="section" style="overflor: hidden;">
  <div class="fixed-wrapper">
    <h1>Company: <small><em><%= @company.name %></em></small></h1>
  </div>
</div>
<div class="container" style="overflow: hidden; margin-top: -.2%; width: auto;">
  <div class="content" style="margin-top: 10%; height: 600px;">
    <ul class="list-group">
      <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">company title</h4>
        <p class="list-group-item-text">company date</p>
      </a>
      <li class="list-group-item">company title</li>
      <li class="list-group-item">company content</li>
      <li class="list-group-item">company date</li>
      <li class="list-group-item">view</li>
      <li class="list-group-item">edit</li>
      <li class="list-grou-item">delete</li>
    </ul>
  </div><!--/.content-->
</div><!--/.container-->