config/routes.rb
LunchPanoply::Application.routes.draw do
  root to: 'static_pages#index'

  devise_for :admins

  devise_for :employees, 
             :controllers => { 
                               # :registration => "registration",
                               :omniauth_callbacks => "employees/omniauth_callbacks" 
                              }

  namespace :api_clients do
    resources :menu_items, defaults: { format: 'json' }
  end                           

  resources :companies

  resources :employees do
    resources :sessions
    resources :comments
    resources :favorites
    # resources :companies
  end

  # resources :companies do
  #   resources :employees
  # end

  resources :venues do
    resources :menu_items
  end

  resources :menu_items

  # resources :menus do
  #   resources :menu_items
  # end

  # resources :sessions, only: [:new, :create, :destroy, :failure]
  # resources :identities
  # match '/auth/:provider/callback', to: 'sessions#create'

  # match '/signup',  to: 'employees#new', as: :sign_up
  # match '/signout', to: 'sessions#destroy', as: :signout
  # match '/signin',  to: 'sessions#new', as: :signin

  # match '/auth/failure', to: 'sessions#failure'

  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_auth_nav.html.erb
<ul class="nav nav-pages">
  <% if employee_signed_in? %>
    <li style="margin-left: -30%; margin-top: 20%;">
      <%= button_to(
                     'Logout', 
                     destroy_employee_session_path, 
                     method: :delete,
                     class: 'btn btn-sm btn-default'
                    ) %>
    </li>
  <% else %>
    <li>
      <span>
        <h5>
          <%= link_to('Login', new_employee_session_path) %>
          -or-
          <%= link_to(
                       'Sign up', 
                       new_employee_registration_path,
                       class: 'label label-default'
                      ) %>
          &nbsp;&nbsp;&nbsp;&nbsp;
        </h5>
      </span>
    </li>
  <% end %>
</ul>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div id="alert" class="section>
    <div class="fixed-wrapper">
      <div class="alert class="close data-dismiss="alert">
        <div class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">x</button>
          <h3><%= type.capitalize %></h3> <p><%= message %></p>
        </div>   
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sub_nav.html.erb
<%#= link_to 'Sign in with Facebook', employee_omniauth_authorize_path(:facebook) %>
<nav class="" style="overflow-x: hidden; overflow-y: scroll;">
<div id="navbar" class="navbar navbar-inverse navbar-fixed-top" %>
<!--   <div class="navbar-inner">

      <a href="#" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-th-list"></span>
      </a>

  </div> -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Lunch Panoply', root_path, class: 'navbar-brand' %>
  </div>
  <div class="collapse navbar-collapse" style="margin-top: 0%;">
    <ul class="nav navbar-nav">
      <!-- This hidden one just makes scrollspy reset when going above the team section -->
      <li style="display: none;"><a href="#home"></a><i class="icon-home"></i>HOME</li>
      <span class="arror-left"></span>
      <li>
        <%= link_to menu_items_path, class: 'scroll'  do %>
          <i class="icon-list"></i>ENTREES<span class="arrow-left"></span>
        <% end %>
      </li>
      <li>
        <%= link_to venues_path, class: 'scroll'  do %>
          <i class="icon-food"></i>VENUES<span class="arrow-left"></span>
        <% end %>
      </li>
<!--       <li>
        <%#= link_to employee_comments_path(@employee), class: 'scroll' do %>
          <i class="icon-comments"></i>COMMENTS<span class="arrow-left"></span>
        <%# end %>
      </li> -->
    </ul>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LunchPanoply</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Font Awesome Icons -->
    <!-- <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
 
    
    <!-- Bootstrap core CSS -->
    <!-- <link href="../assets/stylesheets/bootstrap-theme.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="../assets/stylesheets/font-awesome.min.css"> -->
    
    <!-- Montserrat: http://www.google.com/fonts/#QuickUsePlace:quickUse/Family:Montserrat -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat:700,100' rel='stylesheet' type='text/css'>
        
    <!-- Stylesheet -->
    <!-- <link href="../stylesheets/style.css" rel="stylesheet"> -->
    <!--[if lt IE 9]>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    
    
    <span>   
      <%= render 'layouts/sub_nav', locals: { employee: @employee } %>
      <%= render 'layouts/flash_messages', flash: flash %>
      <%= yield %>
      <%#= render 'layouts/footer' %>
    </span>
  </body>
</html>